#!/bin/zsh

sync_alacritty_colors() {
	cp "$HOME/.config/alacritty/colors/suckless-light.toml" ./alacritty/
	cp "$HOME/.config/alacritty/colors/suckless-dark.toml" ./alacritty/
	cp "$HOME/.config/alacritty/colors/suckless-blue.toml" ./alacritty/
}

sync_tmux_colors() {
	cp "$HOME/.config/tmux/colors/suckless-light.conf" ./tmux/
	cp "$HOME/.config/tmux/colors/suckless-dark.conf" ./tmux/
	cp "$HOME/.config/tmux/colors/suckless-blue.conf" ./tmux/
}

sync_vim_colors() {
	cp "$HOME/.vim/colors/suckless-light.vim" ./vim/
	cp "$HOME/.vim/colors/suckless-dark.vim" ./vim/
	cp "$HOME/.vim/colors/suckless-blue.vim" ./vim/
}

set -x # verbose mode on
sync_alacritty_colors
sync_tmux_colors
sync_vim_colors
set +x # verbose mode off
